# Team 1 - UFC Fighters


![](https://cdn.vox-cdn.com/thumbor/z_CMbdCm8HZrJh-lKL3GGjSKM-8=/0x0:2440x1627/1200x800/filters:focal(1212x228:1602x618)/cdn.vox-cdn.com/uploads/chorus_image/image/65759283/110_Robbie_Lawler_x_Ben_Askren.0.jpg)

_For more information about the dataset, read [here](https://www.kaggle.com/rajeevw/ufcdata)._

## Your tasks
- Name your team!
- Read the source and do some quick research to understand more about the dataset and its topic
- Clean the data
- Perform Exploratory Data Analysis on the dataset
- Analyze the data more deeply and extract insights

## Submission Guide
- Create a Github repository for your project
- Upload the dataset (.csv file) and the Jupyter Notebook to your Github repository.
- Submit your works through Google Form (Link to be provided later)

## Tips for Data Cleaning, Manipulation & Visualization
- Here are some of our tips for Data Cleaning, Manipulation & Visualization. [Click here](https://hackmd.io/cBNV7E6TT2WMliQC-GTw1A)

In [0]:
# Start your codes here!

In [1]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

sns.set_style("whitegrid")

In [0]:

matches = pd.read_csv('/content/drive/My Drive/FTMLE - Tonga/Week_3/assignments/datasets/01-ufc-fight/matches.csv')

In [0]:
df = matches [[ 'B_avg_opp_LEG_landed',
'B_avg_opp_PASS',
'B_avg_opp_REV',
'B_avg_opp_SIG_STR_att',
'B_avg_opp_SIG_STR_landed',
'B_avg_opp_SIG_STR_pct',
'B_avg_opp_SUB_ATT',
'B_avg_opp_TD_att',
'B_avg_opp_TD_landed',
'B_avg_opp_TD_pct',
'B_avg_opp_TOTAL_STR_att',
'B_avg_opp_TOTAL_STR_landed',
'B_total_rounds_fought',
'B_total_time_fought(seconds)',
'B_total_title_bouts',
'B_win_by_Decision_Majority',
'B_win_by_Decision_Split',
'B_win_by_Decision_Unanimous',
'B_win_by_KO/TKO',
'B_win_by_Submission',
'B_win_by_TKO_Doctor_Stoppage',
'B_wins',
'B_Stance',
'B_Height_cms',
'B_Reach_cms',
'B_Weight_lbs',
'R_current_lose_streak',
'R_current_win_streak',
'R_draw',
'R_avg_BODY_att',
'R_avg_BODY_landed',
'R_avg_CLINCH_att',
'R_avg_CLINCH_landed',
'R_avg_DISTANCE_att',
'R_avg_DISTANCE_landed',
'R_avg_GROUND_att',
'R_avg_GROUND_landed',
'R_avg_HEAD_att',
'R_avg_HEAD_landed',
'R_avg_KD',
'R_avg_LEG_att',
'R_avg_LEG_landed',
'R_avg_PASS',
'R_avg_REV',
'R_avg_SIG_STR_att',
'R_avg_SIG_STR_landed',
'R_avg_SIG_STR_pct',
'R_avg_SUB_ATT',
'R_avg_TD_att',
'R_avg_TD_landed'
 ]]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5144 entries, 0 to 5143
Data columns (total 50 columns):
B_avg_opp_LEG_landed            3879 non-null float64
B_avg_opp_PASS                  3879 non-null float64
B_avg_opp_REV                   3879 non-null float64
B_avg_opp_SIG_STR_att           3879 non-null float64
B_avg_opp_SIG_STR_landed        3879 non-null float64
B_avg_opp_SIG_STR_pct           3879 non-null float64
B_avg_opp_SUB_ATT               3879 non-null float64
B_avg_opp_TD_att                3879 non-null float64
B_avg_opp_TD_landed             3879 non-null float64
B_avg_opp_TD_pct                3879 non-null float64
B_avg_opp_TOTAL_STR_att         3879 non-null float64
B_avg_opp_TOTAL_STR_landed      3879 non-null float64
B_total_rounds_fought           5144 non-null float64
B_total_time_fought(seconds)    3879 non-null float64
B_total_title_bouts             5144 non-null float64
B_win_by_Decision_Majority      5144 non-null float64
B_win_by_Decision_Split         5144 non-null float64
B_win_by_Decision_Unanimous     5144 non-null float64
B_win_by_KO/TKO                 5144 non-null float64
B_win_by_Submission             5144 non-null float64
B_win_by_TKO_Doctor_Stoppage    5144 non-null float64
B_wins                          5144 non-null float64
B_Stance                        4985 non-null object
B_Height_cms                    5136 non-null float64
B_Reach_cms                     4478 non-null float64
B_Weight_lbs                    5138 non-null float64
R_current_lose_streak           5144 non-null float64
R_current_win_streak            5144 non-null float64
R_draw                          5144 non-null float64
R_avg_BODY_att                  4494 non-null float64
R_avg_BODY_landed               4494 non-null float64
R_avg_CLINCH_att                4494 non-null float64
R_avg_CLINCH_landed             4494 non-null float64
R_avg_DISTANCE_att              4494 non-null float64
R_avg_DISTANCE_landed           4494 non-null float64
R_avg_GROUND_att                4494 non-null float64
R_avg_GROUND_landed             4494 non-null float64
R_avg_HEAD_att                  4494 non-null float64
R_avg_HEAD_landed               4494 non-null float64
R_avg_KD                        4494 non-null float64
R_avg_LEG_att                   4494 non-null float64
R_avg_LEG_landed                4494 non-null float64
R_avg_PASS                      4494 non-null float64
R_avg_REV                       4494 non-null float64
R_avg_SIG_STR_att               4494 non-null float64
R_avg_SIG_STR_landed            4494 non-null float64
R_avg_SIG_STR_pct               4494 non-null float64
R_avg_SUB_ATT                   4494 non-null float64
R_avg_TD_att                    4494 non-null float64
R_avg_TD_landed                 4494 non-null float64
dtypes: float64(49), object(1)
memory usage: 2.0+ MB

In [11]:
df[df['B_Stance'].isnull()].sample(10)

      B_avg_opp_LEG_landed  B_avg_opp_PASS  ...  R_avg_TD_att  R_avg_TD_landed
5029                   NaN             NaN  ...           NaN              NaN
281                    NaN             NaN  ...           NaN              NaN
2917                   NaN             NaN  ...           NaN              NaN
433               6.666667        0.000000  ...      7.416667         2.666667
3028                   NaN             NaN  ...           NaN              NaN
2652                   NaN             NaN  ...           NaN              NaN
2510             19.000000        0.333333  ...      7.000000         1.000000
1978              5.000000        1.000000  ...      2.000000         1.000000
3034                   NaN             NaN  ...           NaN              NaN
275                    NaN             NaN  ...           NaN              NaN

[10 rows x 50 columns]

In [12]:
df.isnull().sum()

B_avg_opp_LEG_landed            1265
B_avg_opp_PASS                  1265
B_avg_opp_REV                   1265
B_avg_opp_SIG_STR_att           1265
B_avg_opp_SIG_STR_landed        1265
B_avg_opp_SIG_STR_pct           1265
B_avg_opp_SUB_ATT               1265
B_avg_opp_TD_att                1265
B_avg_opp_TD_landed             1265
B_avg_opp_TD_pct                1265
B_avg_opp_TOTAL_STR_att         1265
B_avg_opp_TOTAL_STR_landed      1265
B_total_rounds_fought              0
B_total_time_fought(seconds)    1265
B_total_title_bouts                0
B_win_by_Decision_Majority         0
B_win_by_Decision_Split            0
B_win_by_Decision_Unanimous        0
B_win_by_KO/TKO                    0
B_win_by_Submission                0
B_win_by_TKO_Doctor_Stoppage       0
B_wins                             0
B_Stance                         159
B_Height_cms                       8
B_Reach_cms                      666
B_Weight_lbs                       6
R_current_lose_streak              0
R_current_win_streak               0
R_draw                             0
R_avg_BODY_att                   650
R_avg_BODY_landed                650
R_avg_CLINCH_att                 650
R_avg_CLINCH_landed              650
R_avg_DISTANCE_att               650
R_avg_DISTANCE_landed            650
R_avg_GROUND_att                 650
R_avg_GROUND_landed              650
R_avg_HEAD_att                   650
R_avg_HEAD_landed                650
R_avg_KD                         650
R_avg_LEG_att                    650
R_avg_LEG_landed                 650
R_avg_PASS                       650
R_avg_REV                        650
R_avg_SIG_STR_att                650
R_avg_SIG_STR_landed             650
R_avg_SIG_STR_pct                650
R_avg_SUB_ATT                    650
R_avg_TD_att                     650
R_avg_TD_landed                  650
dtype: int64

In [0]:
df.drop(labels=df[df['B_Stance'].isnull()].index,inplace=True)

In [0]:
df.fillna(value=0,inplace=True)

In [17]:
df.isnull().sum()

B_avg_opp_LEG_landed            0
B_avg_opp_PASS                  0
B_avg_opp_REV                   0
B_avg_opp_SIG_STR_att           0
B_avg_opp_SIG_STR_landed        0
B_avg_opp_SIG_STR_pct           0
B_avg_opp_SUB_ATT               0
B_avg_opp_TD_att                0
B_avg_opp_TD_landed             0
B_avg_opp_TD_pct                0
B_avg_opp_TOTAL_STR_att         0
B_avg_opp_TOTAL_STR_landed      0
B_total_rounds_fought           0
B_total_time_fought(seconds)    0
B_total_title_bouts             0
B_win_by_Decision_Majority      0
B_win_by_Decision_Split         0
B_win_by_Decision_Unanimous     0
B_win_by_KO/TKO                 0
B_win_by_Submission             0
B_win_by_TKO_Doctor_Stoppage    0
B_wins                          0
B_Stance                        0
B_Height_cms                    0
B_Reach_cms                     0
B_Weight_lbs                    0
R_current_lose_streak           0
R_current_win_streak            0
R_draw                          0
R_avg_BODY_att                  0
R_avg_BODY_landed               0
R_avg_CLINCH_att                0
R_avg_CLINCH_landed             0
R_avg_DISTANCE_att              0
R_avg_DISTANCE_landed           0
R_avg_GROUND_att                0
R_avg_GROUND_landed             0
R_avg_HEAD_att                  0
R_avg_HEAD_landed               0
R_avg_KD                        0
R_avg_LEG_att                   0
R_avg_LEG_landed                0
R_avg_PASS                      0
R_avg_REV                       0
R_avg_SIG_STR_att               0
R_avg_SIG_STR_landed            0
R_avg_SIG_STR_pct               0
R_avg_SUB_ATT                   0
R_avg_TD_att                    0
R_avg_TD_landed                 0
dtype: int64

In [18]:
df.sample(20)

      B_avg_opp_LEG_landed  B_avg_opp_PASS  ...  R_avg_TD_att  R_avg_TD_landed
4086              0.000000           2.000  ...      3.428571         2.142857
4258              3.800000           4.000  ...      6.600000         0.800000
168               0.000000           0.000  ...      2.000000         0.000000
811               6.000000           0.000  ...      7.428571         3.285714
3827              4.571429           2.000  ...      3.500000         0.000000
688               6.000000           1.000  ...      6.666667         3.333333
4443              3.600000           0.200  ...      5.666667         3.666667
3925              3.600000           1.000  ...      2.000000         0.000000
1745              5.000000           0.000  ...     10.000000         2.400000
2900              0.000000           0.000  ...      0.000000         0.000000
1199              8.800000           0.400  ...      3.333333         1.666667
3531              0.000000           0.000  ...      0.000000         0.000000
2601              1.400000           2.600  ...      5.000000         2.666667
206               0.000000           0.000  ...      0.666667         0.333333
4224              2.333333           3.000  ...      1.625000         0.625000
2174              3.625000           0.875  ...      5.500000         1.333333
1348              5.250000           0.375  ...      2.636364         0.727273
2179             26.500000           0.500  ...      0.000000         0.000000
2157              0.000000           0.000  ...      2.000000         1.500000
4554              1.833333           0.500  ...      8.750000         2.500000

[20 rows x 50 columns]

In [19]:
df.describe()

       B_avg_opp_LEG_landed  B_avg_opp_PASS  ...  R_avg_TD_att  R_avg_TD_landed
count           4985.000000     4985.000000  ...   4985.000000      4985.000000
mean               3.612651        0.829420  ...      2.675232         1.156084
std                4.375029        1.340217  ...      2.805778         1.241176
min                0.000000        0.000000  ...      0.000000         0.000000
25%                0.000000        0.000000  ...      0.500000         0.000000
50%                2.466667        0.333333  ...      2.000000         0.888889
75%                5.500000        1.076923  ...      4.000000         1.769231
max               50.000000       19.000000  ...     30.000000        11.000000

[8 rows x 49 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4985 entries, 0 to 5143
Data columns (total 50 columns):
B_avg_opp_LEG_landed            4985 non-null float64
B_avg_opp_PASS                  4985 non-null float64
B_avg_opp_REV                   4985 non-null float64
B_avg_opp_SIG_STR_att           4985 non-null float64
B_avg_opp_SIG_STR_landed        4985 non-null float64
B_avg_opp_SIG_STR_pct           4985 non-null float64
B_avg_opp_SUB_ATT               4985 non-null float64
B_avg_opp_TD_att                4985 non-null float64
B_avg_opp_TD_landed             4985 non-null float64
B_avg_opp_TD_pct                4985 non-null float64
B_avg_opp_TOTAL_STR_att         4985 non-null float64
B_avg_opp_TOTAL_STR_landed      4985 non-null float64
B_total_rounds_fought           4985 non-null float64
B_total_time_fought(seconds)    4985 non-null float64
B_total_title_bouts             4985 non-null float64
B_win_by_Decision_Majority      4985 non-null float64
B_win_by_Decision_Split         4985 non-null float64
B_win_by_Decision_Unanimous     4985 non-null float64
B_win_by_KO/TKO                 4985 non-null float64
B_win_by_Submission             4985 non-null float64
B_win_by_TKO_Doctor_Stoppage    4985 non-null float64
B_wins                          4985 non-null float64
B_Stance                        4985 non-null object
B_Height_cms                    4985 non-null float64
B_Reach_cms                     4985 non-null float64
B_Weight_lbs                    4985 non-null float64
R_current_lose_streak           4985 non-null float64
R_current_win_streak            4985 non-null float64
R_draw                          4985 non-null float64
R_avg_BODY_att                  4985 non-null float64
R_avg_BODY_landed               4985 non-null float64
R_avg_CLINCH_att                4985 non-null float64
R_avg_CLINCH_landed             4985 non-null float64
R_avg_DISTANCE_att              4985 non-null float64
R_avg_DISTANCE_landed           4985 non-null float64
R_avg_GROUND_att                4985 non-null float64
R_avg_GROUND_landed             4985 non-null float64
R_avg_HEAD_att                  4985 non-null float64
R_avg_HEAD_landed               4985 non-null float64
R_avg_KD                        4985 non-null float64
R_avg_LEG_att                   4985 non-null float64
R_avg_LEG_landed                4985 non-null float64
R_avg_PASS                      4985 non-null float64
R_avg_REV                       4985 non-null float64
R_avg_SIG_STR_att               4985 non-null float64
R_avg_SIG_STR_landed            4985 non-null float64
R_avg_SIG_STR_pct               4985 non-null float64
R_avg_SUB_ATT                   4985 non-null float64
R_avg_TD_att                    4985 non-null float64
R_avg_TD_landed                 4985 non-null float64
dtypes: float64(49), object(1)
memory usage: 1.9+ MB

In [0]:
from google.colab import files
df.to_csv('nguyet.csv',index=False) 
files.download('nguyet.csv')

In [23]:
cd sample_data/

/content/sample_data

In [24]:
ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*